### ISSUE TITLE
Error: Argument 2 must be length 3, not 2

### ISSUE THREAD

**Issue by bjoern-1** [rsquaredacademy/rbin#40]
when I use rbin_quantiles(data, response, predictors[i], bins=3) on my dataset, there is an error "Error: Argument 2 must be length 3, not 2"
rbin_quantiles(data, response, predictors[i], bins=2) works just fine

> summary(Data$CONVERSION) #response
     0      1 
248996  24912 

>summary(Data$COUNT_VISITS_6M) #predictors[i]
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    2.00   10.64   11.00  707.00 

I hope this helps!

**Comment by aravindhebbali** [comment]
If I am correct, you are running this inside a loop right? I will need more information to debug this.  Is it possible to share anonymized data or a reproducible example?

**Comment by bjoern-1** [comment]
I sent you the files yestertday. Did you receive them?

**Comment by aravindhebbali** [comment]
> 
> 
> I sent you the files yestertday. Did you receive them?

To which email address have you sent the files? Pls send them to either hebbali.aravind@gmail.com or pkgs@rsquaredacademy.com

**Comment by aravindhebbali** [comment]
> 
> 
> > I sent you the files yestertday. Did you receive them?
> 
> To which email address have you sent the files? Pls send them to either [hebbali.aravind@gmail.com](mailto:hebbali.aravind@gmail.com) or [pkgs@rsquaredacademy.com](mailto:pkgs@rsquaredacademy.com)

Received the files. Will look into them and get back to you.

**Comment by bjoern-1** [comment]
many thanks for the quick response! 👍

**Comment by aravindhebbali** [comment]
Hi @bjoern-1.. I looked at the data you sent. It is extremely skewed and hence the error when trying to bin using quantiles.

#### Percentiles

```
> descriptr::ds_percentiles(data, COUNT_VISITS_6M)
# A tibble: 1 x 12
  var               min  per1  per5 per10    q1 median    q3 per95 per90 per99   max
  <chr>           <int> <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <int>
1 COUNT_VISITS_6M     0     0     0     0     0      2     9    44    27   110   464
```

#### Histogram

```
hist(data$COUNT_VISITS_6M, col = "blue")
```
![Rplot](https://user-images.githubusercontent.com/8706536/63841610-bf1fe680-c9a0-11e9-9ea5-0c81b0b2c9f8.png)

As you had said earlier, only 2 bins will be created using `rbin_quantiles()`. 

```
> rbin::rbin_quantiles(data, BESTELLER_ZIEL, COUNT_VISITS_6M, 2)
Binning Summary
-----------------------------
Method               Quantile 
Response             BESTELLER_ZIEL 
Predictor            COUNT_VISITS_6M 
Bins                 2 
Count                10000 
Goods                847 
Bads                 9153 
Entropy              0.4 
Information Value    0.42 


# A tibble: 2 x 7
  cut_point bin_count  good   bad    woe    iv entropy
  <chr>         <int> <int> <int>  <dbl> <dbl>   <dbl>
1 < 2            4897   178  4719  0.897 0.274   0.225
2 >= 2           5103   669  4434 -0.489 0.149   0.560
```

I manually ran the underlying code of `rbin_quantiles()` to create 10 bins. Since the data is skewed, it had created 6 bins but had skipped the first 4 as the values of the predictor are 0. 

![manual](https://user-images.githubusercontent.com/8706536/63841752-01e1be80-c9a1-11e9-819c-405781cf4ed7.png)

I would suggest that you use `rbin_manual()` and specify the cut points yourself. Hope this helps.

**Comment by bjoern-1** [comment]
Hi @aravindhebbali, thank you very much for your assist! I see, it's better to bin the data with `rbin_manual()`
